version: "3"
services: # 服务列表
    node: # node 服务
        build: . # Dockerfile 的目录，用于构建镜像
        container_name: node-server-1 # 容器名称
        ports: # 暴露的端口
            - "3000:3000"
        restart: always # 自动重启
        environment: # 设置环境变量
            - NODE_ENV=production
        # command: npm run start # 覆盖容器启动后默认执行的命令
